using System.IO;
using IPTS.Helpers;
using iText.Html2pdf;
using iText.Kernel.Pdf;
using iText.Layout;
using iText.Layout.Element;
using iText.Layout.Properties;

namespace IPTS.Services
{
    public class PdfPrintService
    {
        public byte[] GeneratePdf(HttpUser httpUser, string htmlContent, string title = "Report")
        {
            using MemoryStream ms = new();
            ConverterProperties props = new();
            HtmlConverter.ConvertToPdf(htmlContent, ms, props);
            string logMessage = $"PDF generated by {httpUser.userName} (ID: {httpUser.userId}, IP: {httpUser.ip}) with title '{title}'";
            LogHelper.LogWithContext(logMessage, httpUser.userId, "", "PdfPrintService", Serilog.Events.LogEventLevel.Error);
            return ms.ToArray();
        }
    }
}