using System.IO;
using IPTS.Helpers;
using IPTS.Resources;
using iText.Html2pdf;
using iText.Kernel.Pdf;
using iText.Layout;
using iText.Layout.Element;
using iText.Layout.Properties;

namespace IPTS.Services
{
    public class PdfPrintService
    {
        private readonly LocService _locService;

        public PdfPrintService(LocService locService)
        {
            _locService = locService;
        }

        public byte[] GeneratePdf(HttpUser httpUser, string htmlContent, string title = null)
        {
            if (title == null)
            {
                title = _locService.GetSystem("Label_Report");
            }
                
            
            using MemoryStream ms = new();
            ConverterProperties props = new();
            HtmlConverter.ConvertToPdf(htmlContent, ms, props);
            string logMessage = $"PDF generated by {httpUser.userName} (ID: {httpUser.userId}, IP: {httpUser.ip}) with title '{title}'";
            LogHelper.LogWithContext(logMessage, httpUser.userId, "", "PdfPrintService", Serilog.Events.LogEventLevel.Error);
            return ms.ToArray();
        }
    }
}